FROM ubuntu
RUN apt-get update && apt-get upgrade -y
RUN apt-get -y install git
RUN apt-get -y install sudo
RUN apt install -y curl
RUN curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash -
RUN apt-get install -y nodejs

WORKDIR /home/app/

RUN git clone https://github.com/RuanPS01/valoro-store-products-api.git
RUN cd valoro-store-products-api

WORKDIR /home/app/valoro-store-products-api

RUN npm install
COPY . .

EXPOSE 3001
CMD ["NODE_ENV=dev", "nest", "start"]