FROM ubuntu
RUN apt-get update && apt-get upgrade -y
RUN apt-get -y install git
RUN apt-get -y install vite
RUN apt-get -y install sudo
RUN apt install -y curl
RUN curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash -
RUN apt-get install -y nodejs
RUN npm install --global yarn



WORKDIR /home/app

RUN git clone https://github.com/RuanPS01/valoro-store-web.git
RUN cd valoro-store-web

WORKDIR /home/app/valoro-store-web

RUN yarn
COPY . .

EXPOSE 5173

CMD ["vite"]